version: '3'

services:
  tor-bridge:
    build: .
    ports:
      - "9001:9001"    # ORPort for incoming Tor client connections
      - "9050:9050"    # SOCKS port for local use
    volumes:
      - ./torrc:/etc/tor/torrc  # Bind mount the torrc file
    restart: always
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0  # Allow binding to ports below 1024
